# Generated by Django 4.0.1 on 2022-11-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_listofstatementfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='statement_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.listofstatementfiles'),
        ),
    ]
