# Generated by Django 4.0.1 on 2022-11-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_bankstatement_statement_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfStatementFiles',
            new_name='Statement',
        ),
        migrations.RenameModel(
            old_name='BankStatement',
            new_name='Transaction',
        ),

    ]
    atomic = False
